export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const GET_PRODUCTS_DATA = "GET_PRODUCTS_DATA";
export const GET_PRODUCTS_DATA_TO_BUY = "GET_PRODUCTS_DATA_TO_BUY";
export const USER_LOGIN = "USER_LOGIN";